
@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

LessonList *-->"*" Lesson
Lesson *-->"1" Student
Lesson *-->"1" Subject
Lesson *-->"1" Level
Lesson *-->"1" Day
Lesson *-->"1" LessonTime
Lesson *-->"1" Rate
Lesson *-->"1" Address
@enduml
