
@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor PAYMENT_COLOR
skinparam classBackgroundColor PAYMENT_COLOR

enum Status {
  PAID
  UNPAID
  OVERDUE
}
class Payment
class TotalAmount
class YearMonth
class UnpaidAmount

PaymentList *-->"*" Payment
PaymentList *-->"1" Status
Payment *-->"1" TotalAmount
Payment *-->"1" UnpaidAmount
Payment *-->"1" YearMonth
@enduml
