
@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor PAYMENT_COLOR
skinparam classBackgroundColor PAYMENT_COLOR

class "<<enumeration>>\nStatus" as Status
class Payment
class TotalAmount
class YearMonth
class UnpaidAmount
class "{abstract}\nAmount" as Amount

PaymentList *-->"*" Payment
PaymentList *-->"1" Status
Payment *-->"1" TotalAmount
Payment *-->"1" UnpaidAmount
Payment *-->"1" YearMonth

Amount <|-- TotalAmount
Amount <|-- UnpaidAmount
@enduml
